version: '3.9'

services:
  api:
    container_name: expense-tracker-api
    build:
      context: .
      target: install-deps
    volumes:
      - ./src:/app/src
    ports:
      - 8080:3000
    env_file:
      - .env
    command: yarn start:dev
